const {launch, mockApp} = require('./fixture.cjs');
const assert = require('node:assert/strict');
(async () => {
  const browser = await launch();
  const context = await browser.newContext({viewport: {width: 390, height: 844}});
  const iso = d => new Intl.DateTimeFormat('en-CA', {timeZone: 'Europe/Moscow', year: 'numeric', month: '2-digit', day: '2-digit'}).format(d);
  const at = new Date(iso(new Date()) + 'T12:00:00+03:00'); at.setUTCDate(at.getUTCDate() + 1); const day = iso(at);
  at.setUTCDate(at.getUTCDate() + 1); const nextDay = iso(at);
  let published, publications = 0;
  await mockApp(context, 'https://review.test', async route => {
      const request = route.request(), url = new URL(request.url());
      let body = [];
    if (url.pathname === '/api/v1/me') body = {user: {id: 1, assistant: true, username: 'assistant'}, csrf_token: 'test'};
    if (url.pathname === '/api/v1/homeworks') body = [{id: 1, number: 1, title: 'ДЗ №1', defense_dates: [day, nextDay]}];
    if (url.pathname === '/api/v1/assistant/windows') body = [{id: 1, homework_id: 1, homework_title: 'ДЗ №1', starts_at: nextDay+'T18:00:00+03:00', ends_at: nextDay+'T19:30:00+03:00', status: 'published', booking_count: 0, slot_count: 11}];
    if (url.pathname === '/api/v1/assistant/windows' && request.method() === 'POST') {publications++; published = route.request().postDataJSON(); body = {id: 1};}
    await route.fulfill({json: body});
  });
  const page = await context.newPage(), errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('https://review.test', {waitUntil: 'domcontentloaded'});
  await page.getByRole('button', {name: 'Добавить окно', exact: true}).first().click();
  const reception = page.locator('section').filter({has: page.getByRole('heading', {name: 'Окно приёма', exact: true})});
  assert.equal(await reception.getByLabel('Длительность одного слота, минут', {exact: true}).count(), 1);
  const review = page.locator('section').filter({has: page.getByRole('heading', {name: 'Ревью слотов', exact: true})});
  assert.equal(await review.count(), 1);
  await page.locator('.month-calendar [data-day="' + day + '"]').click();
  assert.equal(await page.locator('.review-table tbody tr').count(), 11);
  // Picking another day replaces the previous selection and its preview.
  await page.locator('.month-calendar [data-day="' + nextDay + '"]').click();
  assert.equal(await page.locator('.month-calendar [aria-pressed="true"]').count(), 1);
  assert.equal(await page.locator('.month-calendar [data-day="' + day + '"]').getAttribute('aria-pressed'), 'false');
  assert.equal(await page.locator('.review-table tbody tr').count(), 11);
  await page.locator('.month-calendar [data-day="' + nextDay + '"]').click();
  assert.equal(await page.locator('.month-calendar [aria-pressed="true"]').count(), 1);
  // One window per form; overlap with an existing window remains allowed.
  assert.equal(await page.getByRole('button', {name: 'Опубликовать', exact: true}).isDisabled(), false);
  assert.equal(await page.getByLabel('Начало: часы', {exact: true}).count(), 1);
  assert.equal(await page.getByLabel('Конец: часы', {exact: true}).count(), 1);
  // End before/equal to start must not silently become an overnight window.
  await page.locator('#content').getByLabel('Конец: часы', {exact: true}).selectOption('18');
  await page.locator('#content').getByLabel('Конец: минуты', {exact: true}).selectOption('00');
  await page.getByRole('alert').getByText('Окончание должно быть позже начала', {exact: true}).waitFor();
  assert.equal(await page.getByRole('button', {name: 'Опубликовать', exact: true}).isDisabled(), true);
  await page.locator('#content').getByLabel('Конец: часы', {exact: true}).selectOption('17');
  assert.equal(await page.locator('.review-table tbody tr').count(), 0);
  assert.equal(await page.getByRole('button', {name: 'Опубликовать', exact: true}).isDisabled(), true);
  await page.locator('#content').getByLabel('Конец: часы', {exact: true}).selectOption('19');
  await page.locator('#content').getByLabel('Конец: минуты', {exact: true}).selectOption('30');
  assert.equal(await page.locator('.review-table tbody tr').count(), 11);
  await page.locator('#content').getByLabel('Начало: минуты', {exact: true}).selectOption('08');
  assert.equal(await page.locator('#content').getByLabel('Конец: минуты', {exact: true}).inputValue(), '30');
  assert.equal(await page.locator('.review-table tbody tr').count(), 10);
  await page.locator('#content').getByLabel('Начало: минуты', {exact: true}).selectOption('00');
  await page.locator('#content').getByLabel('Конец: минуты', {exact: true}).selectOption('20');
  assert.equal(await page.locator('#content').getByLabel('Начало: минуты', {exact: true}).inputValue(), '00');
  assert.equal(await page.locator('.review-table tbody tr').count(), 10);
  await page.locator('#content').getByLabel('Конец: минуты', {exact: true}).selectOption('30');
  await page.getByLabel('Длительность одного слота, минут', {exact: true}).fill('10');
  await page.getByLabel('Длительность одного слота, минут', {exact: true}).blur();
  assert.equal(await page.locator('.review-table tbody tr').count(), 9);
  await page.getByLabel('Длительность одного слота, минут', {exact: true}).fill('8');
  await page.getByLabel('Длительность одного слота, минут', {exact: true}).blur();
  assert.equal(await page.locator('.review-table tbody tr').count(), 11);
  await page.getByRole('button', {name: 'Удалить слот 18:32–18:40', exact: true}).click();
  assert.equal(await page.locator('.review-table tbody tr').count(), 10);
  assert.equal(await page.locator('.review-table').getByText('18:40', {exact: true}).count(), 1);
  await page.getByLabel('Комментарий к защите (необязательно)', {exact: true}).fill('Ссылка: https://meet.example/defense');
  assert.equal(await page.locator('.review-table tbody tr').count(), 10);
  await page.getByRole('button', {name: 'Вернуть удалённые слоты', exact: true}).click();
  assert.equal(await page.locator('.review-table tbody tr').count(), 11);
  await page.getByRole('button', {name: 'Удалить слот 18:32–18:40', exact: true}).click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'review overflows mobile');
  await page.getByRole('button', {name: 'Опубликовать', exact: true}).click();
  await page.getByText('Окно опубликовано', {exact: true}).waitFor();
  assert.equal(iso(new Date(published.starts_at)), nextDay);
  assert.deepEqual(published.excluded_slot_indices, [4]);
  assert.equal(published.comment, 'Ссылка: https://meet.example/defense');
  // Another window is created through a fresh form, with no extra interval state.
  await page.getByRole('button', {name: 'Добавить окно', exact: true}).click();
  await page.getByLabel('Начало: часы', {exact: true}).waitFor();
  assert.equal(await page.getByLabel('Начало: часы', {exact: true}).count(), 1);
  assert.equal(await page.getByLabel('Комментарий к защите (необязательно)', {exact: true}).inputValue(), '');
  await page.locator('.month-calendar [data-day="' + nextDay + '"]').click();
  await page.getByLabel('Конец: часы', {exact: true}).selectOption('21');
  await page.getByLabel('Конец: минуты', {exact: true}).selectOption('00');
  await page.getByLabel('Начало: часы', {exact: true}).selectOption('20');
  await page.getByRole('button', {name: 'Опубликовать', exact: true}).click();
  await page.getByText('Окно опубликовано', {exact: true}).waitFor();
  assert.equal(publications, 2);
  assert.deepEqual(published.excluded_slot_indices, []);
  assert.equal(published.comment, '');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: assistant review table, remove/restore, comment preserves deletion, payload exclusions. Local assets, mocked API.');
})().catch(e => {console.error(e); process.exit(1);});
